services:
  db:
    image: mysql:8.4.5
    environment:
      MYSQL_DATABASE: QueueManagement
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    security_opt:
      - seccomp:unconfined

# No volume for /var/lib/mysql!